# From rp2040 template repo:
# https://github.com/rp-rs/rp2040-project-template
#
# Choose a default "cargo run" tool.
# probe-run is recommended if you have a debugger
# elf2uf2-rs loads firmware over USB when the rp2040 is in boot mode
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip RP2040"
#runner = "elf2uf2-rs -d"
#runner = "gdb-multiarch -q -x openocd.gdb"

rustflags = [
  #"-C", "linker=flip-link",
  #"-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",

  # Code-size optimizations.
  #   trap unreachable can save a lot of space, but requires nightly compiler.
  #   uncomment the next line if you wish to enable it
  # "-Z", "trap-unreachable=no",
  "-C", "inline-threshold=5",
  "-C", "no-vectorize-loops",
]

[build]
target = "thumbv6m-none-eabi"